(* Generated at Tue 11 Dec 2018 09:47:36 *)
{{"diagram_SSS_t1g1n1_FFF", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> S, 
   Field[4] -> F, Field[5] -> F, Field[6] -> F}, 
  {Cp[-F[Index[Generic, 4]], -F[Index[Generic, 5]], S[Index[Generic, 1]]][
    PR], Cp[F[Index[Generic, 5]], F[Index[Generic, 6]], S[Index[Generic, 3]]][
    PL], Cp[-F[Index[Generic, 6]], F[Index[Generic, 4]], 
     S[Index[Generic, 2]]][PL], Cp[-F[Index[Generic, 4]], 
     -F[Index[Generic, 5]], S[Index[Generic, 1]]][PL], 
   Cp[F[Index[Generic, 5]], F[Index[Generic, 6]], S[Index[Generic, 3]]][PR], 
   Cp[-F[Index[Generic, 6]], F[Index[Generic, 4]], S[Index[Generic, 2]]][
    PR]}, {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], 
    Field[5]}, {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSS_t1g2n2_SSS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> S, 
   Field[4] -> S, Field[5] -> S, Field[6] -> S}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -S[Index[Generic, 5]]][1], 
   Cp[S[Index[Generic, 2]], S[Index[Generic, 4]], -S[Index[Generic, 6]]][1], 
   Cp[S[Index[Generic, 3]], S[Index[Generic, 5]], S[Index[Generic, 6]]][1]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], Field[5]}, 
   {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSS_t1g3n3_UUU", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> S, 
   Field[4] -> U, Field[5] -> U, Field[6] -> U}, 
  {Cp[S[Index[Generic, 1]], -U[Index[Generic, 4]], -U[Index[Generic, 5]]][1], 
   Cp[S[Index[Generic, 2]], -U[Index[Generic, 6]], U[Index[Generic, 4]]][1], 
   Cp[S[Index[Generic, 3]], U[Index[Generic, 5]], U[Index[Generic, 6]]][1]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], Field[5]}, 
   {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSS_t1g4n4_SSV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> S, 
   Field[4] -> S, Field[5] -> S, Field[6] -> V}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -S[Index[Generic, 5]]][1], 
   Cp[S[Index[Generic, 2]], S[Index[Generic, 4]], -V[Index[Generic, 6]]][
    Mom[S[Index[Generic, 2]]] - Mom[S[Index[Generic, 4]]]], 
   Cp[S[Index[Generic, 3]], S[Index[Generic, 5]], V[Index[Generic, 6]]][
    Mom[S[Index[Generic, 3]]] - Mom[S[Index[Generic, 5]]]]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], Field[5]}, 
   {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSS_t1g5n5_SVS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> S, 
   Field[4] -> S, Field[5] -> V, Field[6] -> S}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -V[Index[Generic, 5]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 4]]]], 
   Cp[S[Index[Generic, 2]], S[Index[Generic, 4]], -S[Index[Generic, 6]]][1], 
   Cp[S[Index[Generic, 3]], S[Index[Generic, 6]], V[Index[Generic, 5]]][
    Mom[S[Index[Generic, 3]]] - Mom[S[Index[Generic, 6]]]]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], Field[5]}, 
   {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSS_t1g6n6_VSS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> S, 
   Field[4] -> V, Field[5] -> S, Field[6] -> S}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 5]], -V[Index[Generic, 4]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 5]]]], 
   Cp[S[Index[Generic, 2]], -S[Index[Generic, 6]], V[Index[Generic, 4]]][
    Mom[S[Index[Generic, 2]]] - Mom[-S[Index[Generic, 6]]]], 
   Cp[S[Index[Generic, 3]], S[Index[Generic, 5]], S[Index[Generic, 6]]][1]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], Field[5]}, 
   {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSS_t1g7n7_SVV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> S, 
   Field[4] -> S, Field[5] -> V, Field[6] -> V}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -V[Index[Generic, 5]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 4]]]], 
   Cp[S[Index[Generic, 2]], S[Index[Generic, 4]], -V[Index[Generic, 6]]][
    Mom[S[Index[Generic, 2]]] - Mom[S[Index[Generic, 4]]]], 
   Cp[S[Index[Generic, 3]], V[Index[Generic, 5]], V[Index[Generic, 6]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSS_t1g8n8_VSV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> S, 
   Field[4] -> V, Field[5] -> S, Field[6] -> V}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 5]], -V[Index[Generic, 4]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 5]]]], 
   Cp[S[Index[Generic, 2]], V[Index[Generic, 4]], -V[Index[Generic, 6]]][
    g[lt2, lt3]], Cp[S[Index[Generic, 3]], S[Index[Generic, 5]], 
     V[Index[Generic, 6]]][Mom[S[Index[Generic, 3]]] - 
     Mom[S[Index[Generic, 5]]]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSS_t1g9n9_VVS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> S, 
   Field[4] -> V, Field[5] -> V, Field[6] -> S}, 
  {Cp[S[Index[Generic, 1]], -V[Index[Generic, 4]], -V[Index[Generic, 5]]][
    g[lt2, lt3]], Cp[S[Index[Generic, 2]], -S[Index[Generic, 6]], 
     V[Index[Generic, 4]]][Mom[S[Index[Generic, 2]]] - 
     Mom[-S[Index[Generic, 6]]]], 
   Cp[S[Index[Generic, 3]], S[Index[Generic, 6]], V[Index[Generic, 5]]][
    Mom[S[Index[Generic, 3]]] - Mom[S[Index[Generic, 6]]]]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], Field[5]}, 
   {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSS_t1g10n10_VVV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> S, 
   Field[4] -> V, Field[5] -> V, Field[6] -> V}, 
  {Cp[S[Index[Generic, 1]], -V[Index[Generic, 4]], -V[Index[Generic, 5]]][
    g[lt2, lt3]], Cp[S[Index[Generic, 2]], V[Index[Generic, 4]], 
     -V[Index[Generic, 6]]][g[lt2, lt3]], 
   Cp[S[Index[Generic, 3]], V[Index[Generic, 5]], V[Index[Generic, 6]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSS_t2g1n11_SS", {{0, 0, 0, 1, 0}, {0, 0, 0, 0, 1}, 
   {0, 0, 0, 0, 1}, {1, 0, 0, 0, 2}, {0, 1, 1, 2, 0}}, 
  {{1, 4} -> Field[1], {2, 5} -> Field[2], {3, 5} -> Field[3], 
   {4, 5} -> Field[4], {4, 5} -> Field[5]}, {Field[1] -> S, Field[2] -> S, 
   Field[3] -> S, Field[4] -> S, Field[5] -> S}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -S[Index[Generic, 5]]][1], 
   Cp[S[Index[Generic, 2]], S[Index[Generic, 3]], S[Index[Generic, 4]], 
     S[Index[Generic, 5]]][1]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[3]], AntiField[Field[4]], AntiField[Field[5]]}}}, 
 {"diagram_SSS_t2g2n12_VV", {{0, 0, 0, 1, 0}, {0, 0, 0, 0, 1}, 
   {0, 0, 0, 0, 1}, {1, 0, 0, 0, 2}, {0, 1, 1, 2, 0}}, 
  {{1, 4} -> Field[1], {2, 5} -> Field[2], {3, 5} -> Field[3], 
   {4, 5} -> Field[4], {4, 5} -> Field[5]}, {Field[1] -> S, Field[2] -> S, 
   Field[3] -> S, Field[4] -> V, Field[5] -> V}, 
  {Cp[S[Index[Generic, 1]], -V[Index[Generic, 4]], -V[Index[Generic, 5]]][
    g[lt2, lt3]], Cp[S[Index[Generic, 2]], S[Index[Generic, 3]], 
     V[Index[Generic, 4]], V[Index[Generic, 5]]][g[lt3, lt4]]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], Field[5]}, 
   {AntiField[Field[2]], AntiField[Field[3]], AntiField[Field[4]], 
    AntiField[Field[5]]}}}, {"diagram_SSS_t3g1n13_SS", 
  {{0, 0, 0, 1, 0}, {0, 0, 0, 0, 1}, {0, 0, 0, 1, 0}, {1, 0, 1, 0, 2}, 
   {0, 1, 0, 2, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 4} -> Field[3], {5, 4} -> Field[4], {5, 4} -> Field[5]}, 
  {Field[1] -> S, Field[2] -> S, Field[3] -> S, Field[4] -> S, 
   Field[5] -> S}, {Cp[S[Index[Generic, 2]], -S[Index[Generic, 4]], 
     -S[Index[Generic, 5]]][1], Cp[S[Index[Generic, 1]], 
     S[Index[Generic, 3]], S[Index[Generic, 4]], S[Index[Generic, 5]]][1]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], AntiField[Field[3]], 
    AntiField[Field[4]], AntiField[Field[5]]}, {AntiField[Field[2]], 
    AntiField[AntiField[Field[4]]], AntiField[AntiField[Field[5]]]}}}, 
 {"diagram_SSS_t3g2n14_VV", {{0, 0, 0, 1, 0}, {0, 0, 0, 0, 1}, 
   {0, 0, 0, 1, 0}, {1, 0, 1, 0, 2}, {0, 1, 0, 2, 0}}, 
  {{1, 4} -> Field[1], {2, 5} -> Field[2], {3, 4} -> Field[3], 
   {5, 4} -> Field[4], {5, 4} -> Field[5]}, {Field[1] -> S, Field[2] -> S, 
   Field[3] -> S, Field[4] -> V, Field[5] -> V}, 
  {Cp[S[Index[Generic, 2]], -V[Index[Generic, 4]], -V[Index[Generic, 5]]][
    g[lt2, lt3]], Cp[S[Index[Generic, 1]], S[Index[Generic, 3]], 
     V[Index[Generic, 4]], V[Index[Generic, 5]]][g[lt3, lt4]]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], AntiField[Field[3]], 
    AntiField[Field[4]], AntiField[Field[5]]}, {AntiField[Field[2]], 
    AntiField[AntiField[Field[4]]], AntiField[AntiField[Field[5]]]}}}, 
 {"diagram_SSS_t4g1n15_SS", {{0, 0, 0, 1, 0}, {0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 1}, {1, 1, 0, 0, 2}, {0, 0, 1, 2, 0}}, 
  {{1, 4} -> Field[1], {2, 4} -> Field[2], {3, 5} -> Field[3], 
   {5, 4} -> Field[4], {5, 4} -> Field[5]}, {Field[1] -> S, Field[2] -> S, 
   Field[3] -> S, Field[4] -> S, Field[5] -> S}, 
  {Cp[S[Index[Generic, 3]], -S[Index[Generic, 4]], -S[Index[Generic, 5]]][1], 
   Cp[S[Index[Generic, 1]], S[Index[Generic, 2]], S[Index[Generic, 4]], 
     S[Index[Generic, 5]]][1]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], AntiField[Field[2]], AntiField[Field[4]], 
    AntiField[Field[5]]}, {AntiField[Field[3]], 
    AntiField[AntiField[Field[4]]], AntiField[AntiField[Field[5]]]}}}, 
 {"diagram_SSS_t4g2n16_VV", {{0, 0, 0, 1, 0}, {0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 1}, {1, 1, 0, 0, 2}, {0, 0, 1, 2, 0}}, 
  {{1, 4} -> Field[1], {2, 4} -> Field[2], {3, 5} -> Field[3], 
   {5, 4} -> Field[4], {5, 4} -> Field[5]}, {Field[1] -> S, Field[2] -> S, 
   Field[3] -> S, Field[4] -> V, Field[5] -> V}, 
  {Cp[S[Index[Generic, 3]], -V[Index[Generic, 4]], -V[Index[Generic, 5]]][
    g[lt2, lt3]], Cp[S[Index[Generic, 1]], S[Index[Generic, 2]], 
     V[Index[Generic, 4]], V[Index[Generic, 5]]][g[lt3, lt4]]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], AntiField[Field[2]], 
    AntiField[Field[4]], AntiField[Field[5]]}, {AntiField[Field[3]], 
    AntiField[AntiField[Field[4]]], AntiField[AntiField[Field[5]]]}}}, 
 {"diagram_SVV_t1g1n1_FFF", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> V, Field[3] -> V, 
   Field[4] -> F, Field[5] -> F, Field[6] -> F}, 
  {Cp[-F[Index[Generic, 4]], -F[Index[Generic, 5]], S[Index[Generic, 1]]][
    PL], Cp[F[Index[Generic, 5]], F[Index[Generic, 6]], V[Index[Generic, 3]]][
    LorentzProduct[gamma[lt3], PL]], 
   Cp[-F[Index[Generic, 6]], F[Index[Generic, 4]], V[Index[Generic, 2]]][
    LorentzProduct[gamma[lt3], PL]], 
   Cp[-F[Index[Generic, 4]], -F[Index[Generic, 5]], S[Index[Generic, 1]]][
    PR], Cp[F[Index[Generic, 5]], F[Index[Generic, 6]], V[Index[Generic, 3]]][
    LorentzProduct[gamma[lt3], PR]], 
   Cp[-F[Index[Generic, 6]], F[Index[Generic, 4]], V[Index[Generic, 2]]][
    LorentzProduct[gamma[lt3], PR]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SVV_t1g2n2_SSS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> V, Field[3] -> V, 
   Field[4] -> S, Field[5] -> S, Field[6] -> S}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -S[Index[Generic, 5]]][1], 
   Cp[S[Index[Generic, 4]], -S[Index[Generic, 6]], V[Index[Generic, 2]]][
    Mom[S[Index[Generic, 4]]] - Mom[-S[Index[Generic, 6]]]], 
   Cp[S[Index[Generic, 5]], S[Index[Generic, 6]], V[Index[Generic, 3]]][
    Mom[S[Index[Generic, 5]]] - Mom[S[Index[Generic, 6]]]]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], Field[5]}, 
   {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SVV_t1g3n3_UUU", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> V, Field[3] -> V, 
   Field[4] -> U, Field[5] -> U, Field[6] -> U}, 
  {Cp[S[Index[Generic, 1]], -U[Index[Generic, 4]], -U[Index[Generic, 5]]][1], 
   Cp[U[Index[Generic, 5]], U[Index[Generic, 6]], V[Index[Generic, 3]]][
    Mom[U[Index[Generic, 5]]]], Cp[-U[Index[Generic, 6]], 
     U[Index[Generic, 4]], V[Index[Generic, 2]]][
    Mom[-U[Index[Generic, 6]]]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SVV_t1g4n4_SSV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> V, Field[3] -> V, 
   Field[4] -> S, Field[5] -> S, Field[6] -> V}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -S[Index[Generic, 5]]][1], 
   Cp[S[Index[Generic, 4]], V[Index[Generic, 2]], -V[Index[Generic, 6]]][
    g[lt2, lt3]], Cp[S[Index[Generic, 5]], V[Index[Generic, 3]], 
     V[Index[Generic, 6]]][g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SVV_t1g5n5_SVS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> V, Field[3] -> V, 
   Field[4] -> S, Field[5] -> V, Field[6] -> S}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -V[Index[Generic, 5]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 4]]]], 
   Cp[S[Index[Generic, 4]], -S[Index[Generic, 6]], V[Index[Generic, 2]]][
    Mom[S[Index[Generic, 4]]] - Mom[-S[Index[Generic, 6]]]], 
   Cp[S[Index[Generic, 6]], V[Index[Generic, 3]], V[Index[Generic, 5]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SVV_t1g6n6_VSS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> V, Field[3] -> V, 
   Field[4] -> V, Field[5] -> S, Field[6] -> S}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 5]], -V[Index[Generic, 4]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 5]]]], 
   Cp[S[Index[Generic, 5]], S[Index[Generic, 6]], V[Index[Generic, 3]]][
    Mom[S[Index[Generic, 5]]] - Mom[S[Index[Generic, 6]]]], 
   Cp[-S[Index[Generic, 6]], V[Index[Generic, 2]], V[Index[Generic, 4]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SVV_t1g7n7_SVV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> V, Field[3] -> V, 
   Field[4] -> S, Field[5] -> V, Field[6] -> V}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -V[Index[Generic, 5]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 4]]]], 
   Cp[S[Index[Generic, 4]], V[Index[Generic, 2]], -V[Index[Generic, 6]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SVV_t1g8n8_VSV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> V, Field[3] -> V, 
   Field[4] -> V, Field[5] -> S, Field[6] -> V}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 5]], -V[Index[Generic, 4]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 5]]]], 
   Cp[S[Index[Generic, 5]], V[Index[Generic, 3]], V[Index[Generic, 6]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SVV_t1g9n9_VVS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> V, Field[3] -> V, 
   Field[4] -> V, Field[5] -> V, Field[6] -> S}, 
  {Cp[S[Index[Generic, 1]], -V[Index[Generic, 4]], -V[Index[Generic, 5]]][
    g[lt2, lt3]], Cp[-S[Index[Generic, 6]], V[Index[Generic, 2]], 
     V[Index[Generic, 4]]][g[lt2, lt3]], 
   Cp[S[Index[Generic, 6]], V[Index[Generic, 3]], V[Index[Generic, 5]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SVV_t1g10n10_VVV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> V, Field[3] -> V, 
   Field[4] -> V, Field[5] -> V, Field[6] -> V}, 
  {Cp[S[Index[Generic, 1]], -V[Index[Generic, 4]], -V[Index[Generic, 5]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SVV_t2g1n11_SS", {{0, 0, 0, 1, 0}, {0, 0, 0, 0, 1}, 
   {0, 0, 0, 0, 1}, {1, 0, 0, 0, 2}, {0, 1, 1, 2, 0}}, 
  {{1, 4} -> Field[1], {2, 5} -> Field[2], {3, 5} -> Field[3], 
   {4, 5} -> Field[4], {4, 5} -> Field[5]}, {Field[1] -> S, Field[2] -> V, 
   Field[3] -> V, Field[4] -> S, Field[5] -> S}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -S[Index[Generic, 5]]][1], 
   Cp[S[Index[Generic, 4]], S[Index[Generic, 5]], V[Index[Generic, 2]], 
     V[Index[Generic, 3]]][g[lt3, lt4]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[3]], AntiField[Field[4]], AntiField[Field[5]]}}}, 
 {"diagram_SVV_t2g2n12_VV", {{0, 0, 0, 1, 0}, {0, 0, 0, 0, 1}, 
   {0, 0, 0, 0, 1}, {1, 0, 0, 0, 2}, {0, 1, 1, 2, 0}}, 
  {{1, 4} -> Field[1], {2, 5} -> Field[2], {3, 5} -> Field[3], 
   {4, 5} -> Field[4], {4, 5} -> Field[5]}, {Field[1] -> S, Field[2] -> V, 
   Field[3] -> V, Field[4] -> V, Field[5] -> V}, 
  {Cp[S[Index[Generic, 1]], -V[Index[Generic, 4]], -V[Index[Generic, 5]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[3]], AntiField[Field[4]], AntiField[Field[5]]}}}, 
 {"diagram_SVV_t3g1n13_SV", {{0, 0, 0, 1, 0}, {0, 0, 0, 0, 1}, 
   {0, 0, 0, 1, 0}, {1, 0, 1, 0, 2}, {0, 1, 0, 2, 0}}, 
  {{1, 4} -> Field[1], {2, 5} -> Field[2], {3, 4} -> Field[3], 
   {5, 4} -> Field[4], {5, 4} -> Field[5]}, {Field[1] -> S, Field[2] -> V, 
   Field[3] -> V, Field[4] -> S, Field[5] -> V}, 
  {Cp[-S[Index[Generic, 4]], V[Index[Generic, 2]], -V[Index[Generic, 5]]][
    g[lt2, lt3]], Cp[S[Index[Generic, 1]], S[Index[Generic, 4]], 
     V[Index[Generic, 3]], V[Index[Generic, 5]]][g[lt3, lt4]]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], AntiField[Field[3]], 
    AntiField[Field[4]], AntiField[Field[5]]}, {AntiField[Field[2]], 
    AntiField[AntiField[Field[4]]], AntiField[AntiField[Field[5]]]}}}, 
 {"diagram_SVV_t4g1n14_SV", {{0, 0, 0, 1, 0}, {0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 1}, {1, 1, 0, 0, 2}, {0, 0, 1, 2, 0}}, 
  {{1, 4} -> Field[1], {2, 4} -> Field[2], {3, 5} -> Field[3], 
   {5, 4} -> Field[4], {5, 4} -> Field[5]}, {Field[1] -> S, Field[2] -> V, 
   Field[3] -> V, Field[4] -> S, Field[5] -> V}, 
  {Cp[-S[Index[Generic, 4]], V[Index[Generic, 3]], -V[Index[Generic, 5]]][
    g[lt2, lt3]], Cp[S[Index[Generic, 1]], S[Index[Generic, 4]], 
     V[Index[Generic, 2]], V[Index[Generic, 5]]][g[lt3, lt4]]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], AntiField[Field[2]], 
    AntiField[Field[4]], AntiField[Field[5]]}, {AntiField[Field[3]], 
    AntiField[AntiField[Field[4]]], AntiField[AntiField[Field[5]]]}}}, 
 {"diagram_SSV_t1g1n1_FFF", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> V, 
   Field[4] -> F, Field[5] -> F, Field[6] -> F}, 
  {Cp[-F[Index[Generic, 4]], -F[Index[Generic, 5]], S[Index[Generic, 1]]][
    PL], Cp[F[Index[Generic, 5]], F[Index[Generic, 6]], V[Index[Generic, 3]]][
    LorentzProduct[gamma[lt3], PL]], 
   Cp[-F[Index[Generic, 6]], F[Index[Generic, 4]], S[Index[Generic, 2]]][PL], 
   Cp[-F[Index[Generic, 4]], -F[Index[Generic, 5]], S[Index[Generic, 1]]][
    PR], Cp[F[Index[Generic, 5]], F[Index[Generic, 6]], V[Index[Generic, 3]]][
    LorentzProduct[gamma[lt3], PR]], 
   Cp[-F[Index[Generic, 6]], F[Index[Generic, 4]], S[Index[Generic, 2]]][
    PR]}, {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], 
    Field[5]}, {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSV_t1g2n2_SSS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> V, 
   Field[4] -> S, Field[5] -> S, Field[6] -> S}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -S[Index[Generic, 5]]][1], 
   Cp[S[Index[Generic, 2]], S[Index[Generic, 4]], -S[Index[Generic, 6]]][1], 
   Cp[S[Index[Generic, 5]], S[Index[Generic, 6]], V[Index[Generic, 3]]][
    Mom[S[Index[Generic, 5]]] - Mom[S[Index[Generic, 6]]]]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], Field[5]}, 
   {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSV_t1g3n3_UUU", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> V, 
   Field[4] -> U, Field[5] -> U, Field[6] -> U}, 
  {Cp[S[Index[Generic, 1]], -U[Index[Generic, 4]], -U[Index[Generic, 5]]][1], 
   Cp[S[Index[Generic, 2]], -U[Index[Generic, 6]], U[Index[Generic, 4]]][1], 
   Cp[U[Index[Generic, 5]], U[Index[Generic, 6]], V[Index[Generic, 3]]][
    Mom[U[Index[Generic, 5]]]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSV_t1g4n4_SSV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> V, 
   Field[4] -> S, Field[5] -> S, Field[6] -> V}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -S[Index[Generic, 5]]][1], 
   Cp[S[Index[Generic, 2]], S[Index[Generic, 4]], -V[Index[Generic, 6]]][
    Mom[S[Index[Generic, 2]]] - Mom[S[Index[Generic, 4]]]], 
   Cp[S[Index[Generic, 5]], V[Index[Generic, 3]], V[Index[Generic, 6]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSV_t1g5n5_SVS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> V, 
   Field[4] -> S, Field[5] -> V, Field[6] -> S}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -V[Index[Generic, 5]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 4]]]], 
   Cp[S[Index[Generic, 2]], S[Index[Generic, 4]], -S[Index[Generic, 6]]][1], 
   Cp[S[Index[Generic, 6]], V[Index[Generic, 3]], V[Index[Generic, 5]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSV_t1g6n6_VSS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> V, 
   Field[4] -> V, Field[5] -> S, Field[6] -> S}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 5]], -V[Index[Generic, 4]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 5]]]], 
   Cp[S[Index[Generic, 2]], -S[Index[Generic, 6]], V[Index[Generic, 4]]][
    Mom[S[Index[Generic, 2]]] - Mom[-S[Index[Generic, 6]]]], 
   Cp[S[Index[Generic, 5]], S[Index[Generic, 6]], V[Index[Generic, 3]]][
    Mom[S[Index[Generic, 5]]] - Mom[S[Index[Generic, 6]]]]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], Field[5]}, 
   {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSV_t1g7n7_SVV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> V, 
   Field[4] -> S, Field[5] -> V, Field[6] -> V}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -V[Index[Generic, 5]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 4]]]], 
   Cp[S[Index[Generic, 2]], S[Index[Generic, 4]], -V[Index[Generic, 6]]][
    Mom[S[Index[Generic, 2]]] - Mom[S[Index[Generic, 4]]]]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], Field[5]}, 
   {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSV_t1g8n8_VSV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> V, 
   Field[4] -> V, Field[5] -> S, Field[6] -> V}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 5]], -V[Index[Generic, 4]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 5]]]], 
   Cp[S[Index[Generic, 2]], V[Index[Generic, 4]], -V[Index[Generic, 6]]][
    g[lt2, lt3]], Cp[S[Index[Generic, 5]], V[Index[Generic, 3]], 
     V[Index[Generic, 6]]][g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSV_t1g9n9_VVS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> V, 
   Field[4] -> V, Field[5] -> V, Field[6] -> S}, 
  {Cp[S[Index[Generic, 1]], -V[Index[Generic, 4]], -V[Index[Generic, 5]]][
    g[lt2, lt3]], Cp[S[Index[Generic, 2]], -S[Index[Generic, 6]], 
     V[Index[Generic, 4]]][Mom[S[Index[Generic, 2]]] - 
     Mom[-S[Index[Generic, 6]]]], 
   Cp[S[Index[Generic, 6]], V[Index[Generic, 3]], V[Index[Generic, 5]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSV_t1g10n10_VVV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> S, Field[3] -> V, 
   Field[4] -> V, Field[5] -> V, Field[6] -> V}, 
  {Cp[S[Index[Generic, 1]], -V[Index[Generic, 4]], -V[Index[Generic, 5]]][
    g[lt2, lt3]], Cp[S[Index[Generic, 2]], V[Index[Generic, 4]], 
     -V[Index[Generic, 6]]][g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SSV_t2g1n11_SV", {{0, 0, 0, 1, 0}, {0, 0, 0, 0, 1}, 
   {0, 0, 0, 0, 1}, {1, 0, 0, 0, 2}, {0, 1, 1, 2, 0}}, 
  {{1, 4} -> Field[1], {2, 5} -> Field[2], {3, 5} -> Field[3], 
   {4, 5} -> Field[4], {4, 5} -> Field[5]}, {Field[1] -> S, Field[2] -> S, 
   Field[3] -> V, Field[4] -> S, Field[5] -> V}, 
  {Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -V[Index[Generic, 5]]][
    Mom[S[Index[Generic, 1]]] - Mom[-S[Index[Generic, 4]]]], 
   Cp[S[Index[Generic, 2]], S[Index[Generic, 4]], V[Index[Generic, 3]], 
     V[Index[Generic, 5]]][g[lt3, lt4]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[3]], AntiField[Field[4]], AntiField[Field[5]]}}}, 
 {"diagram_SSV_t3g1n12_SV", {{0, 0, 0, 1, 0}, {0, 0, 0, 0, 1}, 
   {0, 0, 0, 1, 0}, {1, 0, 1, 0, 2}, {0, 1, 0, 2, 0}}, 
  {{1, 4} -> Field[1], {2, 5} -> Field[2], {3, 4} -> Field[3], 
   {5, 4} -> Field[4], {5, 4} -> Field[5]}, {Field[1] -> S, Field[2] -> S, 
   Field[3] -> V, Field[4] -> S, Field[5] -> V}, 
  {Cp[S[Index[Generic, 2]], -S[Index[Generic, 4]], -V[Index[Generic, 5]]][
    Mom[S[Index[Generic, 2]]] - Mom[-S[Index[Generic, 4]]]], 
   Cp[S[Index[Generic, 1]], S[Index[Generic, 4]], V[Index[Generic, 3]], 
     V[Index[Generic, 5]]][g[lt3, lt4]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], AntiField[Field[3]], AntiField[Field[4]], 
    AntiField[Field[5]]}, {AntiField[Field[2]], 
    AntiField[AntiField[Field[4]]], AntiField[AntiField[Field[5]]]}}}, 
 {"diagram_SFF_t1g1n1_FFS", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> F, Field[3] -> F, 
   Field[4] -> F, Field[5] -> F, Field[6] -> S}, 
  {Cp[F[Index[Generic, 2]], F[Index[Generic, 4]], -S[Index[Generic, 6]]][PR], 
   Cp[-F[Index[Generic, 4]], -F[Index[Generic, 5]], S[Index[Generic, 1]]][
    PL], Cp[F[Index[Generic, 5]], F[Index[Generic, 3]], S[Index[Generic, 6]]][
    PL], Cp[F[Index[Generic, 2]], F[Index[Generic, 4]], 
     -S[Index[Generic, 6]]][PL], Cp[-F[Index[Generic, 4]], 
     -F[Index[Generic, 5]], S[Index[Generic, 1]]][PR], 
   Cp[F[Index[Generic, 5]], F[Index[Generic, 3]], S[Index[Generic, 6]]][PR]}, 
  {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], Field[5]}, 
   {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SFF_t1g2n2_SSF", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> F, Field[3] -> F, 
   Field[4] -> S, Field[5] -> S, Field[6] -> F}, 
  {Cp[F[Index[Generic, 2]], -F[Index[Generic, 6]], S[Index[Generic, 4]]][PL], 
   Cp[F[Index[Generic, 6]], F[Index[Generic, 3]], S[Index[Generic, 5]]][PL], 
   Cp[F[Index[Generic, 2]], -F[Index[Generic, 6]], S[Index[Generic, 4]]][PR], 
   Cp[F[Index[Generic, 6]], F[Index[Generic, 3]], S[Index[Generic, 5]]][PR], 
   Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -S[Index[Generic, 5]]][
    1]}, {Field[1], Field[2], Field[3], {AntiField[Field[1]], Field[4], 
    Field[5]}, {AntiField[Field[2]], AntiField[Field[4]], Field[6]}, 
   {AntiField[Field[3]], AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SFF_t1g3n3_FFV", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> F, Field[3] -> F, 
   Field[4] -> F, Field[5] -> F, Field[6] -> V}, 
  {Cp[F[Index[Generic, 2]], F[Index[Generic, 4]], -V[Index[Generic, 6]]][
    LorentzProduct[gamma[lt3], PR]], 
   Cp[-F[Index[Generic, 4]], -F[Index[Generic, 5]], S[Index[Generic, 1]]][
    PL], Cp[F[Index[Generic, 2]], F[Index[Generic, 4]], 
     -V[Index[Generic, 6]]][LorentzProduct[gamma[lt3], PL]], 
   Cp[-F[Index[Generic, 4]], -F[Index[Generic, 5]], S[Index[Generic, 1]]][
    PR], Cp[F[Index[Generic, 5]], F[Index[Generic, 3]], V[Index[Generic, 6]]][
    LorentzProduct[gamma[lt3], PL]], 
   Cp[F[Index[Generic, 5]], F[Index[Generic, 3]], V[Index[Generic, 6]]][
    LorentzProduct[gamma[lt3], PR]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SFF_t1g4n4_SVF", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> F, Field[3] -> F, 
   Field[4] -> S, Field[5] -> V, Field[6] -> F}, 
  {Cp[F[Index[Generic, 2]], -F[Index[Generic, 6]], S[Index[Generic, 4]]][PL], 
   Cp[F[Index[Generic, 6]], F[Index[Generic, 3]], V[Index[Generic, 5]]][
    LorentzProduct[gamma[lt3], PL]], 
   Cp[F[Index[Generic, 2]], -F[Index[Generic, 6]], S[Index[Generic, 4]]][PR], 
   Cp[F[Index[Generic, 6]], F[Index[Generic, 3]], V[Index[Generic, 5]]][
    LorentzProduct[gamma[lt3], PR]], 
   Cp[S[Index[Generic, 1]], -S[Index[Generic, 4]], -V[Index[Generic, 5]]][
    Mom[S[1]] - Mom[-S[Index[Generic, 4]]]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SFF_t1g5n5_VSF", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> F, Field[3] -> F, 
   Field[4] -> V, Field[5] -> S, Field[6] -> F}, 
  {Cp[F[Index[Generic, 2]], -F[Index[Generic, 6]], V[Index[Generic, 4]]][
    LorentzProduct[gamma[lt3], PR]], 
   Cp[F[Index[Generic, 6]], F[Index[Generic, 3]], S[Index[Generic, 5]]][PL], 
   Cp[F[Index[Generic, 2]], -F[Index[Generic, 6]], V[Index[Generic, 4]]][
    LorentzProduct[gamma[lt3], PL]], 
   Cp[F[Index[Generic, 6]], F[Index[Generic, 3]], S[Index[Generic, 5]]][PR], 
   Cp[S[Index[Generic, 1]], -S[Index[Generic, 5]], -V[Index[Generic, 4]]][
    Mom[S[1]] - Mom[-S[Index[Generic, 5]]]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}, 
 {"diagram_SFF_t1g6n6_VVF", {{0, 0, 0, 1, 0, 0}, {0, 0, 0, 0, 1, 0}, 
   {0, 0, 0, 0, 0, 1}, {1, 0, 0, 0, 1, 1}, {0, 1, 0, 1, 0, 1}, 
   {0, 0, 1, 1, 1, 0}}, {{1, 4} -> Field[1], {2, 5} -> Field[2], 
   {3, 6} -> Field[3], {4, 5} -> Field[4], {4, 6} -> Field[5], 
   {5, 6} -> Field[6]}, {Field[1] -> S, Field[2] -> F, Field[3] -> F, 
   Field[4] -> V, Field[5] -> V, Field[6] -> F}, 
  {Cp[F[Index[Generic, 2]], -F[Index[Generic, 6]], V[Index[Generic, 4]]][
    LorentzProduct[gamma[lt3], PL]], 
   Cp[F[Index[Generic, 6]], F[Index[Generic, 3]], V[Index[Generic, 5]]][
    LorentzProduct[gamma[lt3], PL]], 
   Cp[F[Index[Generic, 2]], -F[Index[Generic, 6]], V[Index[Generic, 4]]][
    LorentzProduct[gamma[lt3], PR]], 
   Cp[F[Index[Generic, 6]], F[Index[Generic, 3]], V[Index[Generic, 5]]][
    LorentzProduct[gamma[lt3], PR]], 
   Cp[S[Index[Generic, 1]], -V[Index[Generic, 4]], -V[Index[Generic, 5]]][
    g[lt2, lt3]]}, {Field[1], Field[2], Field[3], 
   {AntiField[Field[1]], Field[4], Field[5]}, {AntiField[Field[2]], 
    AntiField[Field[4]], Field[6]}, {AntiField[Field[3]], 
    AntiField[Field[5]], AntiField[Field[6]]}}}}
