function(fs_package_status_message msg)
  message(STATUS "${Blue}${msg}${ColourReset}")
endfunction()

macro(find_optional_package name enable_name)
  if(${enable_name})
    find_package(${name})
    if(${name}_FOUND)
      fs_package_status_message("Enabling use of ${name}")
    else()
      unset(${enable_name})
      fs_package_status_message("Disabling use of ${name}")
    endif()
  else()
    fs_package_status_message("Disabling use of ${name}")
  endif()
endmacro()

function(find_threads)
  set(CMAKE_THREAD_PREFER_PTHREAD TRUE)
  set(THREADS_PREFER_PTHREAD_FLAG TRUE)
  find_optional_package(Threads ENABLE_THREADS)
  if(NOT Threads::Threads)
    add_library(fs_threads INTERFACE)
    add_library(Threads::Threads ALIAS fs_threads)
  endif()
endfunction()

function(find_lapack)
  find_optional_package(LAPACK ENABLE_LAPACK)
endfunction()
