macro(find_optional_package name enable_name)
  if(${enable_name})
    find_package(${name})
    if(${name}_FOUND)
      message(STATUS "Enabling use of ${name}")
    else()
      unset(${enable_name})
      message(STATUS "Disabling use of ${name}")
    endif()
  endif()
endmacro()
